/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-03-11 08:53:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("  \n");
      out.write("\n");
      out.write("/*=========================\n");
      out.write("  Icons\n");
      out.write(" ================= */\n");
      out.write("\n");
      out.write("/* footer social icons */\n");
      out.write("ul.social-network {\n");
      out.write("\tlist-style: none;\n");
      out.write("\tdisplay: inline;\n");
      out.write("\tmargin-left:0 !important;\n");
      out.write("\tpadding: 0;\n");
      out.write("}\n");
      out.write("ul.social-network li {\n");
      out.write("\tdisplay: inline;\n");
      out.write("\tmargin: 0 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* footer social icons */\n");
      out.write(".social-network a.icoRss:hover {\n");
      out.write("\tbackground-color: #F56505;\n");
      out.write("}\n");
      out.write(".social-network a.icoFacebook:hover {\n");
      out.write("\tbackground-color:#3B5998;\n");
      out.write("}\n");
      out.write(".social-network a.icoTwitter:hover {\n");
      out.write("\tbackground-color:#33ccff;\n");
      out.write("}\n");
      out.write(".social-network a.icoGoogle:hover {\n");
      out.write("\tbackground-color:#BD3518;\n");
      out.write("}\n");
      out.write(".social-network a.icoVimeo:hover {\n");
      out.write("\tbackground-color:#0590B8;\n");
      out.write("}\n");
      out.write(".social-network a.icoLinkedin:hover {\n");
      out.write("\tbackground-color:#007bb7;\n");
      out.write("}\n");
      out.write(".social-network a.icoRss:hover i, .social-network a.icoFacebook:hover i, .social-network a.icoTwitter:hover i,\n");
      out.write(".social-network a.icoGoogle:hover i, .social-network a.icoVimeo:hover i, .social-network a.icoLinkedin:hover i {\n");
      out.write("\tcolor:#fff;\n");
      out.write("}\n");
      out.write("a.socialIcon:hover, .socialHoverClass {\n");
      out.write("\tcolor:#44BCDD;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-circle li a {\n");
      out.write("\tdisplay:inline-block;\n");
      out.write("\tposition:relative;\n");
      out.write("\tmargin:0 auto 0 auto;\n");
      out.write("\t-moz-border-radius:50%;\n");
      out.write("\t-webkit-border-radius:50%;\n");
      out.write("\tborder-radius:50%;\n");
      out.write("\ttext-align:center;\n");
      out.write("\twidth: 50px;\n");
      out.write("\theight: 50px;\n");
      out.write("\tfont-size:20px;\n");
      out.write("}\n");
      out.write(".social-circle li i {\n");
      out.write("\tmargin:0;\n");
      out.write("\tline-height:50px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-circle li a:hover i, .triggeredHover {\n");
      out.write("\t-moz-transform: rotate(360deg);\n");
      out.write("\t-webkit-transform: rotate(360deg);\n");
      out.write("\t-ms--transform: rotate(360deg);\n");
      out.write("\ttransform: rotate(360deg);\n");
      out.write("\t-webkit-transition: all 0.2s;\n");
      out.write("\t-moz-transition: all 0.2s;\n");
      out.write("\t-o-transition: all 0.2s;\n");
      out.write("\t-ms-transition: all 0.2s;\n");
      out.write("\ttransition: all 0.2s;\n");
      out.write("}\n");
      out.write(".social-circle i {\n");
      out.write("\tcolor: #fff;\n");
      out.write("\t-webkit-transition: all 0.8s;\n");
      out.write("\t-moz-transition: all 0.8s;\n");
      out.write("\t-o-transition: all 0.8s;\n");
      out.write("\t-ms-transition: all 0.8s;\n");
      out.write("\ttransition: all 0.8s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center><h3>@CopyRight2017</h3>\n");
      out.write("<!--Pulling Awesome Font -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \t\t\t<div class=\"col-md-12\">\n");
      out.write("                    <ul class=\"social-network social-circle\">\n");
      out.write("                        <li><a href=\"#\" class=\"icoRss\" title=\"Rss\" style=\"background-color: #D3D3D4\"><i class=\"fa fa-rss\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"icoFacebook\" title=\"Facebook\" style=\"background-color: #D3D3D4\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"icoTwitter\" title=\"Twitter\" style=\"background-color: #D3D3D4\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"icoGoogle\" title=\"Google +\" style=\"background-color: #D3D3D4\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"icoLinkedin\" title=\"Linkedin\" style=\"background-color: #D3D3D4\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("                    </ul>\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
